################################################################################
#
# batman-adv-legacy-versioned
#
################################################################################

BATMAN_ADV_LEGACY_VERSIONED_VERSION = 64bc6ba3358439a20dfbe72c7016f341befb92f3
BATMAN_ADV_LEGACY_VERSIONED_SITE_METHOD = git
BATMAN_ADV_LEGACY_VERSIONED_SITE = https://github.com/hwhw/batman-adv-legacy.git
BATMAN_ADV_LEGACY_VERSIONED_LICENSE = GPLv2
BATMAN_ADV_LEGACY_VERSIONED_DEPENDENCIES = linux

define BATMAN_ADV_LEGACY_VERSIONED_BUILD_CMDS
	$(MAKE) -C $(@D) $(LINUX_MAKE_FLAGS) KERNELPATH=$(LINUX_DIR) \
		CONFIG_BATMAN_ADV_DEBUG=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_VERSIONED_DEBUG) \
		CONFIG_BATMAN_ADV_BLA=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_VERSIONED_BLA) \
		CONFIG_BATMAN_ADV_DAT=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_VERSIONED_DAT) \
		CONFIG_BATMAN_ADV_NC=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_VERSIONED_NC)
endef

define BATMAN_ADV_LEGACY_VERSIONED_INSTALL_TARGET_CMDS
	$(MAKE) -C $(@D) $(LINUX_MAKE_FLAGS) KERNELPATH=$(LINUX_DIR) \
		CONFIG_BATMAN_ADV_DEBUG=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_VERSIONED_DEBUG) \
		CONFIG_BATMAN_ADV_BLA=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_VERSIONED_BLA) \
		CONFIG_BATMAN_ADV_DAT=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_VERSIONED_DAT) \
		CONFIG_BATMAN_ADV_NC=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_VERSIONED_NC) \
		INSTALL_MOD_PATH=$(TARGET_DIR) \
		install
endef

$(eval $(generic-package))
