#!/bin/sh
case "$1" in
  start)
        [ -b /dev/ubda ] && sh /dev/ubda
        ;;
  stop)
        ;;
  restart|reload)
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
