#!/bin/sh
case "$1" in
  start)
        cat /etc/modules | while read modprobe; do modprobe $modprobe; done
        ;;
  stop)
        ;;
  restart|reload)
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
