#!/bin/sh

source /etc/sysconfig.sh
if [ "$fastd_enabled" != "1" ]; then
    echo "fastd is disabled."
    exit 0
fi

case "$1" in
  start)
        echo -n "Starting fastd: "
        if [ -z "$fastd_secret" ]; then
            /usr/bin/fastd --generate-key > /etc/fastd/key.txt
            fastd_secret=$(awk '/Secret:/ {print $2}' /etc/fastd/key.txt)
            echo -e "\nfastd public key: "$(awk '/Public:/ {print $2}' /etc/fastd/key.txt)
        fi
        if [ "$fastd_anon" == "1" ]; then
            VERIFY="on verify \"true\";"
        fi
        echo "key \"a2822c632f9bdf990d34d612341a2b564bb4785742e9780ca185393034c8559c\";" > /etc/fastd/peers/dummy
        if [ -n "$fastd_limit" ]; then
            LIMIT="peer limit $fastd_limit;"
        fi
        echo "
log to syslog level info;
interface \"mesh-vpn\";
method \"aes128-gcm\";
method \"salsa2012+umac\";
method \"salsa2012+gmac\";
bind 0.0.0.0${fastd_port:+:$fastd_port};
secret \"$fastd_secret\";
mtu ${fastd_mtu:=1406};
status socket \"/var/run/fastd.socket\";
#user \"nobody\";
include peers from \"/etc/fastd/peers\";
$VERIFY
$LIMIT
on up \"/etc/fastd/up.sh\";" > /etc/fastd/fastd.conf

        umask 077
        start-stop-daemon -S -b -q -p /var/run/fastd.pid \
            --exec /usr/bin/fastd -- -c /etc/fastd/fastd.conf
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  stop)
        echo -n "Stopping fastd gateway: "
        start-stop-daemon -K -q -p /var/run/fastd.pid
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  restart|reload)
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
