#!/bin/sh
source /etc/sysconfig.sh
case "$1" in
  start)
        ifup bat0
        ;;
  stop)
        ;;
  restart|reload)
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
